In [7]:
import numpy as np


In [8]:
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [9]:
# 1 answer
print(list_)
# this is the normal list that we use in python
# it's data type is <class 'list'>
# no new library is required for this
print(type(list_))

['1', '2', '3', '4', '5']
<class 'list'>


In [10]:
print(array_list)
# This is an numpy array
# It's data types is <class 'numpy.ndarray'>
# We need to import numpy to use this
print(type(array_list))

['1' '2' '3' '4' '5']
<class 'numpy.ndarray'>


In [11]:
# 2 answer
array_list.dtype

dtype('<U1')

In [12]:
for i in array_list:print(type(i))

<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>
<class 'numpy.str_'>


In [13]:
for i in list_: print(type(i))

<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>
<class 'str'>


In [14]:
# 3 answer
array_list = np.array(object = list_,dtype = int)

In [15]:
array_list.dtype

dtype('int32')

In [16]:
num_list =[[1,2,3],[4,5,6]]
num_array =np.array(object =num_list)
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [17]:
# 4 answer
num_array.shape

(2, 3)

In [18]:
num_array.size

6

In [19]:
# 5 answer
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
np.matrix(np.zeros((3,3)))

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [21]:
# 5 answer
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [22]:
np.matrix(np.eye(5))

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])